services:
  database:
   image: mysql:8.4
   volumes:
     - dbWebService:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   networks:
    - webservice
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  wordpress:
   image: wordpress:6.8.2-apache
   restart: always
   depends_on:
     database:
       condition: service_healthy
   environment:
     WORDPRESS_DB_HOST: database:3306
     WORDPRESS_DB_USER: ${MYSQL_USER}
     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
   networks:
    - webservice
   healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
  nginx:
    image: nginx:1.28-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      wordpress:
        condition: service_healthy

    networks:
      - webservice
networks:
 webservice:
   driver: bridge

volumes:
  dbWebService:
   
