name: Docker Compose CI

on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose file
        run: docker compose config

      - name: Start containers
        run: docker compose up -d
        continue-on-error: true

      - name: Show container logs
        run: docker compose logs

      - name: Wait for services
        run: sleep 30

      - name: Test Nginx
        run: curl -f http://localhost:8080
